CREATE TABLE credito (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito    VARCHAR(50)    NOT NULL UNIQUE,
    numero_nfse       VARCHAR(50)    NOT NULL,
    data_constituicao DATE           NOT NULL,
    valor_issqn       DECIMAL(15, 2) NOT NULL,
    tipo_credito      VARCHAR(50)    NOT NULL,
    simples_nacional  BOOLEAN        NOT NULL,
    aliquota          DECIMAL(5, 2)  NOT NULL,
    valor_faturado    DECIMAL(15, 2) NOT NULL,
    valor_deducao     DECIMAL(15, 2) NOT NULL,
    base_calculo      DECIMAL(15, 2) NOT NULL
);

INSERT INTO credito (numero_credito, numero_nfse, data_constituicao, valor_issqn, tipo_credito, simples_nacional, aliquota, valor_faturado, valor_deducao, base_calculo)
VALUES ('CRED001','NFSE001', CURRENT_DATE, 150.00, 'NORMAL', FALSE, 5.00, 3000.00, 0.00, 3000.00);